add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[Î»](bold red) "
error_symbol = "[Î»](bold green) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ â‡¡ Ã—${count} "
behind = "â‡£ Ã—${count} "
diverged = "â‡• ğŸï¸ â‡¡ Ã—${ahead_count} â‡£ Ã—${behind_count} "
untracked = "ğŸ›¤ï¸  Ã—${count} "
stashed = "ğŸ“¦ "
modified = "! Ã—${count} "
staged = "ğŸ—ƒï¸  Ã—${count} "
renamed = "Â» Ã—${count} "
deleted = "ğŸ—‘ï¸  Ã—${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[nodejs]
format = "[$symbol$version]($style) "
style = "bold green"
